name: Build VideoScheduler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Build main application
      run: |
        python -m nuitka --mingw64 --windows-icon-from-ico=resources/icons/icon.ico --enable-plugin=pyqt5 --onefile --windows-uac-admin --windows-company-name="TRIFY s.r.o." --windows-product-name="Video Scheduler" --windows-file-version="1.22.12.5" --windows-product-version="1.22.12.5" --windows-file-description="TRIFY Video Scheduler" --include-package=requests --include-package=PyQt5 --include-package=vlc --include-qt-plugins=platforms,styles --include-data-dir=resources=resources studio-video_scheduler.py

    - name: Build setup checker
      run: |
        python -m nuitka --mingw64 --windows-icon-from-ico=resources/icons/icon.ico --enable-plugin=pyqt5 --onefile --windows-company-name="TRIFY s.r.o." --windows-product-name="Video Scheduler Setup" --windows-file-version="1.22.12.5" --windows-product-version="1.22.12.5" --windows-file-description="TRIFY Video Scheduler Setup" --include-package=PyQt5 --include-qt-plugins=platforms,styles check_install.py

    - name: Create release package
      run: |
        mkdir release
        copy dist\studio-video_scheduler.exe release\VideoScheduler.exe
        copy dist\check_install.exe release\Setup.exe
        xcopy /E /I resources release\resources
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoScheduler
        path: release\*