name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Download VLC
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.zip" -OutFile "vlc.zip"
        Expand-Archive -Path vlc.zip -DestinationPath .
        dir
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 python-vlc pyinstaller
    
    - name: Build with PyInstaller
      shell: powershell
      run: |
        $Env:Path += ";$pwd\vlc-3.0.18"
        pyinstaller --onefile --noconsole --add-data "vlc-3.0.18/libvlc.dll;." --add-data "vlc-3.0.18/libvlccore.dll;." --add-data "vlc-3.0.18/plugins;plugins" --hidden-import PyQt5.sip studio-video_scheduler.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoScheduler-Windows
        path: dist/studio-video_scheduler.exe
        retention-days: 5
