name: Build VideoScheduler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install auto-py-to-exe
    
    - name: Build with Auto-py-to-exe
      run: |
        python -m auto_py_to_exe --output-dir dist --file studio-video_scheduler.py --onefile --window-based --icon=NONE --name=VideoScheduler --add-data "version_info.txt;." --add-data "app.manifest;."
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoScheduler
        path: dist/VideoScheduler.exe
