name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Download VLC
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.zip" -OutFile "vlc.zip"
        Expand-Archive -Path vlc.zip -DestinationPath ./vlc
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 python-vlc pyinstaller
    
    - name: Build with PyInstaller
      env:
        VLC_APP_PATH: ${{ github.workspace }}\vlc\vlc-3.0.18
      run: |
        pyinstaller --onefile --noconsole --hidden-import PyQt5.sip --add-data "$env:VLC_APP_PATH;vlc" studio-video_scheduler.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoScheduler-Windows
        path: dist/studio-video_scheduler.exe
