name: Build VideoScheduler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        python -m nuitka --mingw64 --windows-disable-console --windows-icon-from-ico=icon.ico --onefile --include-package=requests --include-package=PyQt5 --include-package=vlc --include-qt-plugins=platforms,styles --enable-plugin=pyqt5 studio-video_scheduler.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoScheduler
        path: studio-video_scheduler.exe

